# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: edabackenddaii
service: eventify-eda-be

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  profile: aws-academy
  stage: dev
  role: arn:aws:iam::637423304975:role/LabRole
  vpc:
    securityGroupIds:
      - Ref: PublicSecurityGroup
    subnetIds:
      - Ref: PrivateSubnet1
      - Ref: PrivateSubnet2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource: "arn:aws:execute-api:us-east-1:*:*/*/*/@connections/*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/ConnectionsTable
        - arn:aws:dynamodb:us-east-1:*:table/EventsHistory
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource:
        - arn:aws:events:us-east-1:637423304975:event-bus/default

# Incluir solo estos archivos, necesario para reducir el tamano del zip
package:
  patterns:
    - "!**"
    - "api/rest.py"
    - "api/websocket.py"
    - "api/events.py"
    - "requirements.txt"
    - "utils/save_url.py"

functions:
  testHandler:
    name: TestHandlerLambdaFunction
    handler: api.events.lambda_handler
    package:
      individually: true

  websocketConnect:
    handler: api.websocket.connect
    events:
      - websocket:
          route: $connect

  websocketDisconnect:
    handler: api.websocket.disconnect
    events:
      - websocket:
          route: $disconnect

  websocketDefault:
    handler: api.websocket.default
    events:
      - websocket:
          route: $default

  restApi:
    handler: api.rest.handler
    #package:
    #  individually: true
    #  patterns:
    #      - '!**'
    #      - 'api/rest.py'
    #      - 'requirements.txt'
    events:
      - http:
          path: /v1/health
          method: get
          cors: true
      - http:
          path: /v1/events/history
          method: get
          cors: true
      - http:
          path: /v1/operations/types
          method: get
          cors: true
      - http:
          path: /docs
          method: get
          cors: true
      - http:
          path: /openapi.json
          method: get
          cors: true

  saveWebsocketUrl:
    handler: utils.save_url.lambda_handler
    package:
      individually: true
    timeout: 60

resources:
  Resources:
    MyVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true

    InternetGateway:
      Type: AWS::EC2::InternetGateway

    AttachGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId:
          Ref: MyVPC
        InternetGatewayId:
          Ref: InternetGateway

    PublicSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.1.0/24
        MapPublicIpOnLaunch: true
        AvailabilityZone: us-east-1a

    PublicSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.2.0/24
        MapPublicIpOnLaunch: true
        AvailabilityZone: us-east-1b

    PrivateSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.3.0/24
        MapPublicIpOnLaunch: false
        AvailabilityZone: us-east-1a

    PrivateSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.4.0/24
        MapPublicIpOnLaunch: false
        AvailabilityZone: us-east-1b

    NatGatewayEIP:
      Type: AWS::EC2::EIP
      DependsOn: AttachGateway
      Properties:
        Domain: vpc

    NatGateway:
      Type: AWS::EC2::NatGateway
      Properties:
        AllocationId:
          Fn::GetAtt:
            - NatGatewayEIP
            - AllocationId
        SubnetId:
          Ref: PublicSubnet1

    PrivateRouteTable1:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: MyVPC

    PrivateRouteTable2:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: MyVPC

    PrivateRoute1:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PrivateRouteTable1
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NatGateway

    PrivateRoute2:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PrivateRouteTable2
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NatGateway

    SubnetRouteTableAssociationPrivate1:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: PrivateSubnet1
        RouteTableId:
          Ref: PrivateRouteTable1

    SubnetRouteTableAssociationPrivate2:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: PrivateSubnet2
        RouteTableId:
          Ref: PrivateRouteTable2

    PublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: MyVPC

    PublicRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: InternetGateway

    SubnetRouteTableAssociationPublic1:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: PublicSubnet1
        RouteTableId:
          Ref: PublicRouteTable

    SubnetRouteTableAssociationPublic2:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: PublicSubnet2
        RouteTableId:
          Ref: PublicRouteTable

    PublicSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow all inbound traffic
        VpcId:
          Ref: MyVPC
        SecurityGroupIngress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0

    TestHandlerEventBridgeRule:
      Type: AWS::Events::Rule
      Properties:
        Name: testHandlerEventRule
        EventBusName: default
        EventPattern:
          source:
            - myapp
        Targets:
          - Arn:
              Fn::GetAtt: [TestHandlerLambdaFunction, Arn]
            Id: TestHandlerEventTarget

    TestHandlerLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: TestHandlerLambdaFunction
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com
        SourceArn:
          Fn::GetAtt:
            - TestHandlerEventBridgeRule
            - Arn

    # Permite a otras cuentas de AWS (sandboxes) enviar eventos a este EDA
    EventBusPolicy:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "AllowEventsFromOtherSandboxes"
        EventBusName: "default"
        Action: "events:PutEvents"
        Principal: "747661705570"

    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionsTable
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    EventsHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EventsHistory
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # ApiGatewayBasePathMapping:
    #   Type: AWS::ApiGateway::BasePathMapping
    #   Properties:
    #     DomainName: deliver.ar
    #     RestApiId:
    #       Ref: ApiGatewayRestApi

plugins:
  - serverless-python-requirements
  - serverless-scriptable-plugin
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: true
    useStaticCache: true

  customDomain:
    rest:
      domainName: edaapi.deliver.ar
      stage: dev
      basePath: ""
      certificateName: "*.deliver.ar"
      createRoute53Record: false
      endpointType: REGIONAL
      securityPolicy: tls_1_2
      apiType: rest

    websocket:
      domainName: edaws.deliver.ar
      stage: dev
      basePath: ""
      certificateName: "*.deliver.ar"
      createRoute53Record: false
      endpointType: REGIONAL
      securityPolicy: tls_1_2
      apiType: websocket

  scriptHooks:
    after:deploy:finalize: "aws lambda invoke --function-name eventify-eda-be-dev-saveWebsocketUrl --log-type Tail --profile aws-academy outfile.txt"
